Check pull request commit messages

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,6 +5,20 @@ on:
   - pull_request
 
 jobs:
+  check-commit-messages:
+    if: github.event_name == 'pull_request'
+    permissions:
+      contents: read
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+          persist-credentials: false
+      - uses: airlift/github-actions/check-commit-messages@3cd4cf2f81d921440ab70ae6ad4b507208fecac3 # v1
+        with:
+          base_ref: ${{ github.event.pull_request.base.ref }}
+
   build:
     runs-on: ubuntu-latest
     timeout-minutes: 15
@@ -36,3 +50,18 @@ jobs:
           java-version: 25
       - name: Error Prone Checks
         run: ./mvnw clean compile test-compile -B -V -T 1C -DskipTests -Dair.check.skip-all -P errorprone-compiler
+
+  build-success:
+    if: ${{ always() }} # if `failure()` would not work for cancellations, `!success()` would not work for skipped jobs
+    permissions: {}
+    runs-on: ubuntu-latest
+    needs:
+      - build
+      - check-commit-messages
+      - error-prone
+    steps:
+      - name: "Check results"
+        run: |
+          echo '${{ needs.build.result }}' | grep -xE 'success|skipped' || { echo 'Job "build" failed' >&2; exit 1; }
+          echo '${{ needs.check-commit-messages.result }}' | grep -xE 'success|skipped' || { echo 'Job "check-commit-messages" failed' >&2; exit 1; }
+          echo '${{ needs.error-prone.result }}' | grep -xE 'success|skipped' || { echo 'Job "error-prone" failed' >&2; exit 1; }
